name: test-and-release

# Trigger when a push occurs on main or develop
# Also trigger on tags starting with 'vX.X.X'
on:
  push:
    branches:
      - main
      - develop
    tags:
      - 'v*.*.*'

jobs:
  # Build and Test Job
  # This job runs on every push to main or develop
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            machine: linux
            arch: x64
          - os: windows-latest
            machine: win
            arch: x64

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the solution
        run: dotnet build --configuration Release --no-restore

      - name: Run unit tests with report
        run: dotnet test --configuration Release --no-build


  # Release Job
  # This job runs only on main branch when a tag starting with 'vX.X.X' is pushed
  release:
    needs: test
    if: |
      github.event.base_ref == 'refs/heads/main' &&
      startsWith(github.event.ref, 'refs/tags/v')
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            machine: linux
            arch: x64
          - os: windows-latest
            machine: win
            arch: x64

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v6

      - name: Set Release Variables
        id: vars
        shell: bash
        run: |
          # Extract version (e.g., '1.2.3' from 'v1.2.3')
          VERSION=${GITHUB_REF_NAME#v}
          APP_NAME="SimpleToDoList"
          MACHINE="${{ matrix.machine }}"
          ARCH="${{ matrix.arch }}"
          
          # Determine file extension based on OS
          if [ "${{ runner.os }}" == "Windows" ]; then EXT="zip"; else EXT="tar.gz"; fi
          
          # Construct the full name
          RELEASE_NAME="${APP_NAME}-${VERSION}-${MACHINE}-${ARCH}.${EXT}"
          
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "RELEASE_NAME=$RELEASE_NAME" >> $GITHUB_ENV
          echo "binary_name=$RELEASE_NAME" >> $GITHUB_OUTPUT

      - name: Publish App
        run: |
          dotnet publish src/SimpleToDoList/SimpleToDoList.csproj -c Release -r ${{ matrix.machine }}-${{ matrix.arch }} --self-contained true -o ./publish

      - name: Package Release
        shell: bash
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            7z a ${{ env.RELEASE_NAME }} ./publish/*
          else
            tar -czvf ${{ env.RELEASE_NAME }} -C ./publish .
          fi

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          files: ${{ env.RELEASE_NAME }}
